# Generated by Django 3.2.3 on 2021-06-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('contact', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=30)),
                ('otp', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
