# Generated by Django 3.2.3 on 2021-07-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegisterModel',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('contact', models.IntegerField(unique=True)),
                ('photo', models.ImageField(upload_to='student_images/')),
                ('dob', models.DateField()),
                ('location', models.CharField(max_length=30)),
                ('date_of_reg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
