# Generated by Django 3.2.3 on 2021-07-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app20', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistermodel',
            name='password',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
